#version: '3'
# to use memory limit feature in docker-compose, downgrade version to '2'
version: '2'
services:
  mongo_db:
    build:
      context: ./mongo_db
      dockerfile: Dockerfile
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./mongo_db/data/db:/data/db"
  nginx:
    image: nginx:1.15.11
    ports:
         - "8082:80"
    volumes:
     - "./nginx/conf.d:/etc/nginx/conf.d"
     - "/tmp/upload:/var/www/html"
  app-upload-service:
    # mem_limit: 256M
    image: app-upload-service
    entrypoint: java -jar /app.jar # the jar name is defined in src/main/docker/DockerFile
    ports:
     - "8081:8081"
    volumes:
     - "/tmp/upload:/tmp/upload"
    restart: always
    links:
     - mongo_db
     - nginx
    depends_on:
     - mongo_db
     - nginx