spring:
  profiles:
    active: dev-windows
    #active: dev-linux
  data:
    mongodb:
      # Using custom mongo db config to support more features
      # @see io.aaxis.imageupload.config.CustomMongoConfig
      custom:
        hosts:
          - localhost
        ports:
          - 27017
        username: admin
        password: admin
        database: datawarehouse
        authenticationDatabase: datawarehouse
        connectionPoolMaxSize: 5
        connectionPoolMinSize: 1
        # all time unit is seconds
        connectionPoolMaxWaitTime: 1
        socketConnectTimeout: 1
        socketReadTimeout: 5
        clusterSettingsServerSelectionTimeout: 1
server:
  port: 8081
logging:
  level:
    # loglevel values: @see org.springframework.boot.logging.LogLevel
    # TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    ROOT: DEBUG
    org.springframework: ERROR
    io.aaxis.imageupload: INFO
    org.mongodb: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/imageuploadApp.log
##########################################################
# custom config for package: io.aaxis.imageupload.config
io.aaxis.imageupload.config:
  upload-handler:
    # the request param key of upload files of "handle upload" method
    handleUploadRequestFilesKey: files
    # the success resposne content of "handle upload" method
    handleUploadResponseSuccessMessage: Success
  upload-file-storage:
    # the base folder path of disk saved temp file
    backupFileLocation: "E:\\webflux\\tmp\\upload\\"
    # file suffix of upload successfully
    successUploadFileSuffix: ".done"
    # the location of image in the cloud storage
    imageClouldLocation: "E:\\webflux\\tmp\\upload\\"
  router-config:
    # the image upload API url
    imageUploadUrl: "/upload"
    # the image download API url
    imageDownloadUrl: "/download"
    # the image download API url
    imageTrackUrl: "/track/{trackId}"
  file-part-validator:
    # the file name regular expression
    fileNameRegexp: "^[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+.(bmp|png|cod|gif|ief|jpe|jpeg|jpg|jfif|svg|tif|tiff|ras|cmx|ico|pnm|pbm|pgm|ppm|rgb|xbm|xpm|xwd|mp2|mpa|mpe|mpeg|mpg|mpv2|mov|qt|lsf|lsx|asf|asr|asx|avi|movie)$"
  validation:
    error:
      file-name:
        field: "filename"
        errorCode: "err.fileName.invalid"
        defaultMessage: "The upload file name:[{0}] is invalid"
      files-empty:
        errorCode: "err.files.empty"
        defaultMessage: "The upload file(s) is empty"
      files-list-empty:
        field: "files"
        errorCode: "err.filesList.empty"
        defaultMessage: "The upload list file(s) is empty"
      files-cast:
        field: "files"
        errorCode: "err.files.cast"
        defaultMessage: "The upload file(s) is invalid"
