spring:
  data:
    mongodb:
      custom:
        username: test
        password: 123456
        database: datawarehouse
        authenticationDatabase: datawarehouse
logging:
  level:
    ROOT: INFO
    io.aaxis.imageupload: DEBUG
io.aaxis.imageupload.config:
  upload-handler:
  upload-file-storage:
    backupFileLocation: "/tmp/upload/"
    imageClouldLocation: "/tmp/upload/"
