spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/terrencewei?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123abcABC
        platform: mysql
    batch:
      schema: classpath:schema-mysql.sql