spring:
  application:
    name: order-service
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${eurekaClientServiceUrlDefaultZone}
  instance:
      prefer-ip-address: true